// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.hash.prism.pigeon;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class PrismMediaApi {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum SaveMediaKind {
    WALLPAPER(0),
    SETUP(1);

    final int index;

    SaveMediaKind(final int index) {
      this.index = index;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SaveMediaRequest {
    private @NonNull String link;

    public @NonNull String getLink() {
      return link;
    }

    public void setLink(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"link\" is null.");
      }
      this.link = setterArg;
    }

    private @NonNull Boolean isLocalFile;

    public @NonNull Boolean getIsLocalFile() {
      return isLocalFile;
    }

    public void setIsLocalFile(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"isLocalFile\" is null.");
      }
      this.isLocalFile = setterArg;
    }

    private @NonNull SaveMediaKind kind;

    public @NonNull SaveMediaKind getKind() {
      return kind;
    }

    public void setKind(@NonNull SaveMediaKind setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"kind\" is null.");
      }
      this.kind = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SaveMediaRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SaveMediaRequest that = (SaveMediaRequest) o;
      return link.equals(that.link) && isLocalFile.equals(that.isLocalFile) && kind.equals(that.kind);
    }

    @Override
    public int hashCode() {
      return Objects.hash(link, isLocalFile, kind);
    }

    public static final class Builder {

      private @Nullable String link;

      @CanIgnoreReturnValue
      public @NonNull Builder setLink(@NonNull String setterArg) {
        this.link = setterArg;
        return this;
      }

      private @Nullable Boolean isLocalFile;

      @CanIgnoreReturnValue
      public @NonNull Builder setIsLocalFile(@NonNull Boolean setterArg) {
        this.isLocalFile = setterArg;
        return this;
      }

      private @Nullable SaveMediaKind kind;

      @CanIgnoreReturnValue
      public @NonNull Builder setKind(@NonNull SaveMediaKind setterArg) {
        this.kind = setterArg;
        return this;
      }

      public @NonNull SaveMediaRequest build() {
        SaveMediaRequest pigeonReturn = new SaveMediaRequest();
        pigeonReturn.setLink(link);
        pigeonReturn.setIsLocalFile(isLocalFile);
        pigeonReturn.setKind(kind);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(link);
      toListResult.add(isLocalFile);
      toListResult.add(kind);
      return toListResult;
    }

    static @NonNull SaveMediaRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SaveMediaRequest pigeonResult = new SaveMediaRequest();
      Object link = pigeonVar_list.get(0);
      pigeonResult.setLink((String) link);
      Object isLocalFile = pigeonVar_list.get(1);
      pigeonResult.setIsLocalFile((Boolean) isLocalFile);
      Object kind = pigeonVar_list.get(2);
      pigeonResult.setKind((SaveMediaKind) kind);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DownloadRequest {
    private @NonNull String link;

    public @NonNull String getLink() {
      return link;
    }

    public void setLink(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"link\" is null.");
      }
      this.link = setterArg;
    }

    private @NonNull String filenameWithoutExtension;

    public @NonNull String getFilenameWithoutExtension() {
      return filenameWithoutExtension;
    }

    public void setFilenameWithoutExtension(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"filenameWithoutExtension\" is null.");
      }
      this.filenameWithoutExtension = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DownloadRequest() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DownloadRequest that = (DownloadRequest) o;
      return link.equals(that.link) && filenameWithoutExtension.equals(that.filenameWithoutExtension);
    }

    @Override
    public int hashCode() {
      return Objects.hash(link, filenameWithoutExtension);
    }

    public static final class Builder {

      private @Nullable String link;

      @CanIgnoreReturnValue
      public @NonNull Builder setLink(@NonNull String setterArg) {
        this.link = setterArg;
        return this;
      }

      private @Nullable String filenameWithoutExtension;

      @CanIgnoreReturnValue
      public @NonNull Builder setFilenameWithoutExtension(@NonNull String setterArg) {
        this.filenameWithoutExtension = setterArg;
        return this;
      }

      public @NonNull DownloadRequest build() {
        DownloadRequest pigeonReturn = new DownloadRequest();
        pigeonReturn.setLink(link);
        pigeonReturn.setFilenameWithoutExtension(filenameWithoutExtension);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(link);
      toListResult.add(filenameWithoutExtension);
      return toListResult;
    }

    static @NonNull DownloadRequest fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DownloadRequest pigeonResult = new DownloadRequest();
      Object link = pigeonVar_list.get(0);
      pigeonResult.setLink((String) link);
      Object filenameWithoutExtension = pigeonVar_list.get(1);
      pigeonResult.setFilenameWithoutExtension((String) filenameWithoutExtension);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class OperationResult {
    private @NonNull Boolean success;

    public @NonNull Boolean getSuccess() {
      return success;
    }

    public void setSuccess(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"success\" is null.");
      }
      this.success = setterArg;
    }

    private @Nullable String errorCode;

    public @Nullable String getErrorCode() {
      return errorCode;
    }

    public void setErrorCode(@Nullable String setterArg) {
      this.errorCode = setterArg;
    }

    private @Nullable String message;

    public @Nullable String getMessage() {
      return message;
    }

    public void setMessage(@Nullable String setterArg) {
      this.message = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    OperationResult() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      OperationResult that = (OperationResult) o;
      return success.equals(that.success) && Objects.equals(errorCode, that.errorCode) && Objects.equals(message, that.message);
    }

    @Override
    public int hashCode() {
      return Objects.hash(success, errorCode, message);
    }

    public static final class Builder {

      private @Nullable Boolean success;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccess(@NonNull Boolean setterArg) {
        this.success = setterArg;
        return this;
      }

      private @Nullable String errorCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorCode(@Nullable String setterArg) {
        this.errorCode = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@Nullable String setterArg) {
        this.message = setterArg;
        return this;
      }

      public @NonNull OperationResult build() {
        OperationResult pigeonReturn = new OperationResult();
        pigeonReturn.setSuccess(success);
        pigeonReturn.setErrorCode(errorCode);
        pigeonReturn.setMessage(message);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(success);
      toListResult.add(errorCode);
      toListResult.add(message);
      return toListResult;
    }

    static @NonNull OperationResult fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      OperationResult pigeonResult = new OperationResult();
      Object success = pigeonVar_list.get(0);
      pigeonResult.setSuccess((Boolean) success);
      Object errorCode = pigeonVar_list.get(1);
      pigeonResult.setErrorCode((String) errorCode);
      Object message = pigeonVar_list.get(2);
      pigeonResult.setMessage((String) message);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class DownloadItemsResult {
    private @NonNull Boolean success;

    public @NonNull Boolean getSuccess() {
      return success;
    }

    public void setSuccess(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"success\" is null.");
      }
      this.success = setterArg;
    }

    private @NonNull List<String> items;

    public @NonNull List<String> getItems() {
      return items;
    }

    public void setItems(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"items\" is null.");
      }
      this.items = setterArg;
    }

    private @Nullable String errorCode;

    public @Nullable String getErrorCode() {
      return errorCode;
    }

    public void setErrorCode(@Nullable String setterArg) {
      this.errorCode = setterArg;
    }

    private @Nullable String message;

    public @Nullable String getMessage() {
      return message;
    }

    public void setMessage(@Nullable String setterArg) {
      this.message = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    DownloadItemsResult() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      DownloadItemsResult that = (DownloadItemsResult) o;
      return success.equals(that.success) && items.equals(that.items) && Objects.equals(errorCode, that.errorCode) && Objects.equals(message, that.message);
    }

    @Override
    public int hashCode() {
      return Objects.hash(success, items, errorCode, message);
    }

    public static final class Builder {

      private @Nullable Boolean success;

      @CanIgnoreReturnValue
      public @NonNull Builder setSuccess(@NonNull Boolean setterArg) {
        this.success = setterArg;
        return this;
      }

      private @Nullable List<String> items;

      @CanIgnoreReturnValue
      public @NonNull Builder setItems(@NonNull List<String> setterArg) {
        this.items = setterArg;
        return this;
      }

      private @Nullable String errorCode;

      @CanIgnoreReturnValue
      public @NonNull Builder setErrorCode(@Nullable String setterArg) {
        this.errorCode = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@Nullable String setterArg) {
        this.message = setterArg;
        return this;
      }

      public @NonNull DownloadItemsResult build() {
        DownloadItemsResult pigeonReturn = new DownloadItemsResult();
        pigeonReturn.setSuccess(success);
        pigeonReturn.setItems(items);
        pigeonReturn.setErrorCode(errorCode);
        pigeonReturn.setMessage(message);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(success);
      toListResult.add(items);
      toListResult.add(errorCode);
      toListResult.add(message);
      return toListResult;
    }

    static @NonNull DownloadItemsResult fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      DownloadItemsResult pigeonResult = new DownloadItemsResult();
      Object success = pigeonVar_list.get(0);
      pigeonResult.setSuccess((Boolean) success);
      Object items = pigeonVar_list.get(1);
      pigeonResult.setItems((List<String>) items);
      Object errorCode = pigeonVar_list.get(2);
      pigeonResult.setErrorCode((String) errorCode);
      Object message = pigeonVar_list.get(3);
      pigeonResult.setMessage((String) message);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : SaveMediaKind.values()[((Long) value).intValue()];
        }
        case (byte) 130:
          return SaveMediaRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return DownloadRequest.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return OperationResult.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return DownloadItemsResult.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof SaveMediaKind) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((SaveMediaKind) value).index);
      } else if (value instanceof SaveMediaRequest) {
        stream.write(130);
        writeValue(stream, ((SaveMediaRequest) value).toList());
      } else if (value instanceof DownloadRequest) {
        stream.write(131);
        writeValue(stream, ((DownloadRequest) value).toList());
      } else if (value instanceof OperationResult) {
        stream.write(132);
        writeValue(stream, ((OperationResult) value).toList());
      } else if (value instanceof DownloadItemsResult) {
        stream.write(133);
        writeValue(stream, ((DownloadItemsResult) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface PrismMediaHostApi {

    @NonNull 
    OperationResult saveMedia(@NonNull SaveMediaRequest request);

    @NonNull 
    OperationResult enqueueDownload(@NonNull DownloadRequest request);

    @NonNull 
    DownloadItemsResult listDownloads();

    @NonNull 
    OperationResult clearDownloads();

    /** The codec used by PrismMediaHostApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `PrismMediaHostApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable PrismMediaHostApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable PrismMediaHostApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                SaveMediaRequest requestArg = (SaveMediaRequest) args.get(0);
                try {
                  OperationResult output = api.saveMedia(requestArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                DownloadRequest requestArg = (DownloadRequest) args.get(0);
                try {
                  OperationResult output = api.enqueueDownload(requestArg);
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.listDownloads" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  DownloadItemsResult output = api.listDownloads();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.clearDownloads" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  OperationResult output = api.clearDownloads();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
