import 'package:flutter/widgets.dart';

class JamIcons {
  JamIcons._();

  static const _kFontFam = 'JamIcons';
  static const _kFontPkg = null;

  static const IconData five_hundred_px =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData activity =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airbnb =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock_f =
      IconData(0xe903, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm_clock =
      IconData(0xe904, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_f =
      IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert =
      IconData(0xe906, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alien_f =
      IconData(0xe907, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alien =
      IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_center =
      IconData(0xe909, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_justify =
      IconData(0xe90a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_left =
      IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData align_right =
      IconData(0xe90c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon =
      IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor =
      IconData(0xe90e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_circle =
      IconData(0xe90f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_square =
      IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture =
      IconData(0xe912, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_circle =
      IconData(0xe913, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple_square =
      IconData(0xe914, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple =
      IconData(0xe915, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_f =
      IconData(0xe916, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive =
      IconData(0xe917, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down_f =
      IconData(0xe918, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down_left_f =
      IconData(0xe919, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down_left =
      IconData(0xe91a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down_right_f =
      IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down_right =
      IconData(0xe91c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_down =
      IconData(0xe91d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_left_f =
      IconData(0xe91e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_left =
      IconData(0xe91f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_right_f =
      IconData(0xe920, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_right =
      IconData(0xe921, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up_f =
      IconData(0xe922, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up_left_f =
      IconData(0xe923, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up_left =
      IconData(0xe924, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up_right_f =
      IconData(0xe925, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up_right =
      IconData(0xe926, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_circle_up =
      IconData(0xe927, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_left =
      IconData(0xe928, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_right =
      IconData(0xe929, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down =
      IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      IconData(0xe92b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right =
      IconData(0xe92c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down_f =
      IconData(0xe92d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down_left_f =
      IconData(0xe92e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down_left =
      IconData(0xe92f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down_right_f =
      IconData(0xe930, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down_right =
      IconData(0xe931, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_down =
      IconData(0xe932, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_left_f =
      IconData(0xe933, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_left =
      IconData(0xe934, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_right_f =
      IconData(0xe935, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_right =
      IconData(0xe936, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up_f =
      IconData(0xe937, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up_left_f =
      IconData(0xe938, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up_left =
      IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up_right_f =
      IconData(0xe93a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up_right =
      IconData(0xe93b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_square_up =
      IconData(0xe93c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_left =
      IconData(0xe93d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up_right =
      IconData(0xe93e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_up =
      IconData(0xe93f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_corners =
      IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_fullscreen =
      IconData(0xe941, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_h =
      IconData(0xe942, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrows_v =
      IconData(0xe943, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment =
      IconData(0xe944, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData background_color =
      IconData(0xe945, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backpack_f =
      IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backpack =
      IconData(0xe947, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_circle_f =
      IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_circle =
      IconData(0xe949, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_square_f =
      IconData(0xe94a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward_square =
      IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward =
      IconData(0xe94c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baidu_circle =
      IconData(0xe94d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baidu_square =
      IconData(0xe94e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baidu =
      IconData(0xe94f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandage_f =
      IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandage =
      IconData(0xe951, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart =
      IconData(0xe952, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baseball =
      IconData(0xe953, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball =
      IconData(0xe954, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathtub_f =
      IconData(0xe955, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bathtub =
      IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_charging_f =
      IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_charging =
      IconData(0xe958, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_f =
      IconData(0xe959, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_half_f =
      IconData(0xe95a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_half =
      IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_one_quarter_f =
      IconData(0xe95c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_one_quarter =
      IconData(0xe95d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_three_quarters_f =
      IconData(0xe95e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_three_quarters =
      IconData(0xe95f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery =
      IconData(0xe960, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beatport_circle =
      IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beatport_square =
      IconData(0xe962, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beatport =
      IconData(0xe963, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer_f =
      IconData(0xe964, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer =
      IconData(0xe965, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance_circle =
      IconData(0xe966, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance_square =
      IconData(0xe967, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance =
      IconData(0xe968, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_f =
      IconData(0xe969, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off_f =
      IconData(0xe96a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_off =
      IconData(0xe96b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell =
      IconData(0xe96c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bing_circle =
      IconData(0xe96d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bing_square =
      IconData(0xe96e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bing =
      IconData(0xe96f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday_cake_f =
      IconData(0xe970, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday_cake =
      IconData(0xe971, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_circle =
      IconData(0xe972, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_square =
      IconData(0xe973, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger =
      IconData(0xe974, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth =
      IconData(0xe975, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bold =
      IconData(0xe976, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_f =
      IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book =
      IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_f =
      IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_minus_f =
      IconData(0xe97a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_minus =
      IconData(0xe97b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_plus_f =
      IconData(0xe97c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_plus =
      IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_remove_f =
      IconData(0xe97e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark_remove =
      IconData(0xe97f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark =
      IconData(0xe980, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottle_f =
      IconData(0xe981, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottle =
      IconData(0xe982, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box_f =
      IconData(0xe983, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box =
      IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData branch_f =
      IconData(0xe985, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData branch =
      IconData(0xe986, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_down_f =
      IconData(0xe987, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_down =
      IconData(0xe988, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_up_f =
      IconData(0xe989, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_up =
      IconData(0xe98a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness =
      IconData(0xe98b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_f =
      IconData(0xe98c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush =
      IconData(0xe98d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug_f =
      IconData(0xe98e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bug =
      IconData(0xe98f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_f =
      IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building =
      IconData(0xe991, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus_f =
      IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bus =
      IconData(0xe993, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cactus_f =
      IconData(0xe994, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cactus =
      IconData(0xe995, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator =
      IconData(0xe996, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt_f =
      IconData(0xe997, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt =
      IconData(0xe998, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_f =
      IconData(0xe999, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xe99a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt_f =
      IconData(0xe99b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt =
      IconData(0xe99c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_f =
      IconData(0xe99d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera =
      IconData(0xe99e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candle_f =
      IconData(0xe99f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candle =
      IconData(0xe9a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsule_f =
      IconData(0xe9a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capsule =
      IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car_f =
      IconData(0xe9a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      IconData(0xe9a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData castle_f =
      IconData(0xe9a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData castle =
      IconData(0xe9a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check =
      IconData(0xe9a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down_f =
      IconData(0xe9a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down_left_f =
      IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down_left =
      IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down_right_f =
      IconData(0xe9ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down_right =
      IconData(0xe9ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down =
      IconData(0xe9ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_left_f =
      IconData(0xe9ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_left =
      IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_right_f =
      IconData(0xe9b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_right =
      IconData(0xe9b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up_f =
      IconData(0xe9b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up_left_f =
      IconData(0xe9b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up_left =
      IconData(0xe9b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up_right_f =
      IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up_right =
      IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up =
      IconData(0xe9b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down_left =
      IconData(0xe9b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down_right =
      IconData(0xe9b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_down =
      IconData(0xe9ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left =
      IconData(0xe9bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right =
      IconData(0xe9bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down_f =
      IconData(0xe9bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down_left_f =
      IconData(0xe9be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down_left =
      IconData(0xe9bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down_right_f =
      IconData(0xe9c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down_right =
      IconData(0xe9c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_down =
      IconData(0xe9c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_left_f =
      IconData(0xe9c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_left =
      IconData(0xe9c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_right_f =
      IconData(0xe9c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_right =
      IconData(0xe9c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up_f =
      IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up_left_f =
      IconData(0xe9c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up_left =
      IconData(0xe9c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up_right_f =
      IconData(0xe9ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up_right =
      IconData(0xe9cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_square_up =
      IconData(0xe9cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_left =
      IconData(0xe9cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up_right =
      IconData(0xe9ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_up =
      IconData(0xe9cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down_f =
      IconData(0xe9d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down_left_f =
      IconData(0xe9d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down_left =
      IconData(0xe9d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down_right_f =
      IconData(0xe9d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down_right =
      IconData(0xe9d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_down =
      IconData(0xe9d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_left_f =
      IconData(0xe9d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_left =
      IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_right_f =
      IconData(0xe9d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_right =
      IconData(0xe9d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up_f =
      IconData(0xe9da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up_left_f =
      IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up_left =
      IconData(0xe9dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up_right_f =
      IconData(0xe9dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up_right =
      IconData(0xe9de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_circle_up =
      IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_down_left =
      IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_down_right =
      IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_down =
      IconData(0xe9e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_left =
      IconData(0xe9e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_right =
      IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down_f =
      IconData(0xe9e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down_left_f =
      IconData(0xe9e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down_left =
      IconData(0xe9e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down_right_f =
      IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down_right =
      IconData(0xe9e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_down =
      IconData(0xe9ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_left_f =
      IconData(0xe9eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_left =
      IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_right_f =
      IconData(0xe9ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_right =
      IconData(0xe9ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up_f =
      IconData(0xe9ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up_left_f =
      IconData(0xe9f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up_left =
      IconData(0xe9f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up_right_f =
      IconData(0xe9f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up_right =
      IconData(0xe9f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_square_up =
      IconData(0xe9f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_up_left =
      IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_up_right =
      IconData(0xe9f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevrons_up =
      IconData(0xe9f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chronometer_f =
      IconData(0xe9f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chronometer =
      IconData(0xe9f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_f =
      IconData(0xe9fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle =
      IconData(0xe9fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_format =
      IconData(0xe9fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard_f =
      IconData(0xe9fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard =
      IconData(0xe9fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_f =
      IconData(0xe9ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xea00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle_f =
      IconData(0xea01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle =
      IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_rectangle_f =
      IconData(0xea03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_rectangle =
      IconData(0xea04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close =
      IconData(0xea05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_f =
      IconData(0xea06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_rain_f =
      IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_rain =
      IconData(0xea08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_snow_f =
      IconData(0xea09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_snow =
      IconData(0xea0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_thunder_f =
      IconData(0xea0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_thunder =
      IconData(0xea0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud =
      IconData(0xea0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen_circle =
      IconData(0xea0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen_square =
      IconData(0xea0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen =
      IconData(0xea10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup_f =
      IconData(0xea11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee_cup =
      IconData(0xea12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coffee =
      IconData(0xea13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_f =
      IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog =
      IconData(0xea15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs_f =
      IconData(0xea16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs =
      IconData(0xea17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin_f =
      IconData(0xea18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin =
      IconData(0xea19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color =
      IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass_f =
      IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass =
      IconData(0xea1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer_alt_f =
      IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer_alt =
      IconData(0xea1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer_f =
      IconData(0xea1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData computer =
      IconData(0xea20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card_f =
      IconData(0xea21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card =
      IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crop =
      IconData(0xea23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_f =
      IconData(0xea24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown =
      IconData(0xea25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cutlery_f =
      IconData(0xea26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cutlery =
      IconData(0xea27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cutter_f =
      IconData(0xea28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cutter =
      IconData(0xea29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard_f =
      IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard =
      IconData(0xea2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database_f =
      IconData(0xea2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database =
      IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deezer_circle =
      IconData(0xea2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deezer_square =
      IconData(0xea2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deezer =
      IconData(0xea30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_f =
      IconData(0xea31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete =
      IconData(0xea32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart_circle =
      IconData(0xea33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart_square =
      IconData(0xea34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart =
      IconData(0xea35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digg =
      IconData(0xea36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction_f =
      IconData(0xea37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData direction =
      IconData(0xea38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions_f =
      IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions =
      IconData(0xea3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disc_f =
      IconData(0xea3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disc =
      IconData(0xea3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disqus_circle =
      IconData(0xea3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disqus_square =
      IconData(0xea3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disqus =
      IconData(0xea3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dj_f =
      IconData(0xea40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dj =
      IconData(0xea41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dna =
      IconData(0xea42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_f =
      IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document =
      IconData(0xea44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData door =
      IconData(0xea45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
      IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal_circle =
      IconData(0xea47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal_square =
      IconData(0xea48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal =
      IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ebay =
      IconData(0xea4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData egg_f =
      IconData(0xea4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData egg =
      IconData(0xea4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggs_f =
      IconData(0xea4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eggs =
      IconData(0xea4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject_circle_f =
      IconData(0xea4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject_circle =
      IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject_square_f =
      IconData(0xea51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject_square =
      IconData(0xea52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject =
      IconData(0xea53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_f =
      IconData(0xea54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open_f =
      IconData(0xea55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope_open =
      IconData(0xea56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope =
      IconData(0xea57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extinguisher_f =
      IconData(0xea58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extinguisher =
      IconData(0xea59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_close_f =
      IconData(0xea5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_close =
      IconData(0xea5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_f =
      IconData(0xea5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye =
      IconData(0xea5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyedropper_f =
      IconData(0xea5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyedropper =
      IconData(0xea5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_circle =
      IconData(0xea60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square =
      IconData(0xea61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xea62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward_circle_f =
      IconData(0xea63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward_circle =
      IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward_square_f =
      IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward_square =
      IconData(0xea66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_backward =
      IconData(0xea67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward_circle_f =
      IconData(0xea68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward_circle =
      IconData(0xea69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward_square_f =
      IconData(0xea6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward_square =
      IconData(0xea6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fast_forward =
      IconData(0xea6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather_f =
      IconData(0xea6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather =
      IconData(0xea6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female =
      IconData(0xea6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_f =
      IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file =
      IconData(0xea71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files_f =
      IconData(0xea72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files =
      IconData(0xea73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter_f =
      IconData(0xea74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter =
      IconData(0xea75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint =
      IconData(0xea76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid_f =
      IconData(0xea77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_aid =
      IconData(0xea78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish =
      IconData(0xea79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiverr_circle =
      IconData(0xea7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiverr_square =
      IconData(0xea7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiverr =
      IconData(0xea7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_f =
      IconData(0xea7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xea7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame_f =
      IconData(0xea7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame =
      IconData(0xea80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight_off_f =
      IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight_off =
      IconData(0xea82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight_on_f =
      IconData(0xea83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashlight_on =
      IconData(0xea84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask =
      IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr_circle =
      IconData(0xea86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr_square =
      IconData(0xea87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr =
      IconData(0xea88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flower =
      IconData(0xea89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_f =
      IconData(0xea8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_f =
      IconData(0xea8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open =
      IconData(0xea8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_zip_f =
      IconData(0xea8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_zip =
      IconData(0xea8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder =
      IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData football =
      IconData(0xea90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fork_f =
      IconData(0xea91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fork =
      IconData(0xea92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_circle_f =
      IconData(0xea93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_circle =
      IconData(0xea94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_square_f =
      IconData(0xea95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward_square =
      IconData(0xea96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward =
      IconData(0xea97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare =
      IconData(0xea98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad_f =
      IconData(0xea99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad_retro_f =
      IconData(0xea9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad_retro =
      IconData(0xea9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gamepad =
      IconData(0xea9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost_f =
      IconData(0xea9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost_org_circle =
      IconData(0xea9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost_org_square =
      IconData(0xea9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost_org =
      IconData(0xeaa0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ghost =
      IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_f =
      IconData(0xeaa2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift =
      IconData(0xeaa3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_circle =
      IconData(0xeaa4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_square =
      IconData(0xeaa5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github =
      IconData(0xeaa6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab_circle =
      IconData(0xeaa7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab_square =
      IconData(0xeaa8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab =
      IconData(0xeaa9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_empty =
      IconData(0xeaaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_filled_f =
      IconData(0xeaab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass_filled =
      IconData(0xeaac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glue_f =
      IconData(0xeaad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glue =
      IconData(0xeaae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_circle =
      IconData(0xeaaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play_circle =
      IconData(0xeab0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play_square =
      IconData(0xeab1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play =
      IconData(0xeab2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus_circle =
      IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus_square =
      IconData(0xeab4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus =
      IconData(0xeab5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_square =
      IconData(0xeab6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google =
      IconData(0xeab7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps_f =
      IconData(0xeab8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gps =
      IconData(0xeab9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid_f =
      IconData(0xeaba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid =
      IconData(0xeabb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hairdryer_f =
      IconData(0xeabc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hairdryer =
      IconData(0xeabd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer_f =
      IconData(0xeabe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hammer =
      IconData(0xeabf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtag =
      IconData(0xeac0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_1 =
      IconData(0xeac1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_2 =
      IconData(0xeac2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_3 =
      IconData(0xeac3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_4 =
      IconData(0xeac4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_5 =
      IconData(0xeac5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header_6 =
      IconData(0xeac6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData header =
      IconData(0xeac7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset_f =
      IconData(0xeac8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headset =
      IconData(0xeac9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_f =
      IconData(0xeaca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xeacb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet_f =
      IconData(0xeacc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet =
      IconData(0xeacd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_f =
      IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help =
      IconData(0xeacf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlighter_f =
      IconData(0xead0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlighter =
      IconData(0xead1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history =
      IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_f =
      IconData(0xead3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xead4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_f =
      IconData(0xead5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass =
      IconData(0xead6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream_f =
      IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice_cream =
      IconData(0xead8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card_f =
      IconData(0xead9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData id_card =
      IconData(0xeada, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox_f =
      IconData(0xeadb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inbox =
      IconData(0xeadc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inboxes_f =
      IconData(0xeadd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inboxes =
      IconData(0xeade, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData indent =
      IconData(0xeadf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinite =
      IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_f =
      IconData(0xeae1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xeae2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram =
      IconData(0xeae3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instant_picture_f =
      IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instant_picture =
      IconData(0xeae5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData italic =
      IconData(0xeae6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick_f =
      IconData(0xeae7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joystick =
      IconData(0xeae8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_f =
      IconData(0xeae9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key =
      IconData(0xeaea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_f =
      IconData(0xeaeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard =
      IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language =
      IconData(0xeaed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers_f =
      IconData(0xeaee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers =
      IconData(0xeaef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout_f =
      IconData(0xeaf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layout =
      IconData(0xeaf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf_f =
      IconData(0xeaf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaf =
      IconData(0xeaf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifebuoy_f =
      IconData(0xeaf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lifebuoy =
      IconData(0xeaf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_f =
      IconData(0xeaf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb =
      IconData(0xeaf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line =
      IconData(0xeaf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link =
      IconData(0xeaf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circle =
      IconData(0xeafa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_square =
      IconData(0xeafb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin =
      IconData(0xeafc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_in =
      IconData(0xeafd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out =
      IconData(0xeafe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData luggage_f =
      IconData(0xeaff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData luggage =
      IconData(0xeb00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic_f =
      IconData(0xeb01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magic =
      IconData(0xeb02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet_f =
      IconData(0xeb03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnet =
      IconData(0xeb04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male =
      IconData(0xeb05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_f =
      IconData(0xeb06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_f =
      IconData(0xeb07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker =
      IconData(0xeb08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map =
      IconData(0xeb09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_f =
      IconData(0xeb0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask =
      IconData(0xeb0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal_f =
      IconData(0xeb0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal =
      IconData(0xeb0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medical =
      IconData(0xeb0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_circle =
      IconData(0xeb0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_square =
      IconData(0xeb10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium =
      IconData(0xeb11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu =
      IconData(0xeb12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merge_f =
      IconData(0xeb13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData merge =
      IconData(0xeb14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_alt_f =
      IconData(0xeb15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_alt_writing_f =
      IconData(0xeb16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_alt_writing =
      IconData(0xeb17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_alt =
      IconData(0xeb18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_f =
      IconData(0xeb19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_writing_f =
      IconData(0xeb1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_writing =
      IconData(0xeb1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message =
      IconData(0xeb1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_alt_f =
      IconData(0xeb1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_alt =
      IconData(0xeb1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages_f =
      IconData(0xeb1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messages =
      IconData(0xeb20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger =
      IconData(0xeb21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_alt =
      IconData(0xeb22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_circle_f =
      IconData(0xeb23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_circle =
      IconData(0xeb24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_f =
      IconData(0xeb25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_square_f =
      IconData(0xeb26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_square =
      IconData(0xeb27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic =
      IconData(0xeb28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microchip_f =
      IconData(0xeb29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microchip =
      IconData(0xeb2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle_f =
      IconData(0xeb2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle =
      IconData(0xeb2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_rectangle_f =
      IconData(0xeb2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_rectangle =
      IconData(0xeb2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus =
      IconData(0xeb2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_f =
      IconData(0xeb30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon =
      IconData(0xeb31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horizontal_f =
      IconData(0xeb32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_horizontal =
      IconData(0xeb33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical_f =
      IconData(0xeb34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_vertical =
      IconData(0xeb35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain_f =
      IconData(0xeb36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mountain =
      IconData(0xeb37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move_alt =
      IconData(0xeb38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move =
      IconData(0xeb39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie =
      IconData(0xeb3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mug_f =
      IconData(0xeb3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mug =
      IconData(0xeb3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_f =
      IconData(0xeb3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music =
      IconData(0xeb3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myspace_circle =
      IconData(0xeb3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myspace_square =
      IconData(0xeb40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myspace =
      IconData(0xeb41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napster_circle =
      IconData(0xeb42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napster_square =
      IconData(0xeb43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napster =
      IconData(0xeb44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newsletter_f =
      IconData(0xeb45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newsletter =
      IconData(0xeb46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper_f =
      IconData(0xeb47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData newspaper =
      IconData(0xeb48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData npm =
      IconData(0xeb49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki_circle =
      IconData(0xeb4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki_square =
      IconData(0xeb4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki =
      IconData(0xeb4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera_circle =
      IconData(0xeb4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera_square =
      IconData(0xeb4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opera =
      IconData(0xeb4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ordered_list =
      IconData(0xeb50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_alt_f =
      IconData(0xeb51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_alt_open_f =
      IconData(0xeb52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_alt_open =
      IconData(0xeb53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_alt =
      IconData(0xeb54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_f =
      IconData(0xeb55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_open_f =
      IconData(0xeb56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock_open =
      IconData(0xeb57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData padlock =
      IconData(0xeb58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane_f =
      IconData(0xeb59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane =
      IconData(0xeb5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon_circle =
      IconData(0xeb5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon_square =
      IconData(0xeb5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon =
      IconData(0xeb5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause =
      IconData(0xeb5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal_circle =
      IconData(0xeb5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal_square =
      IconData(0xeb60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal =
      IconData(0xeb61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen_f =
      IconData(0xeb62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen =
      IconData(0xeb63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_f =
      IconData(0xeb64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil =
      IconData(0xeb65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periscope_circle =
      IconData(0xeb66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periscope_square =
      IconData(0xeb67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periscope =
      IconData(0xeb68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_f =
      IconData(0xeb69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone =
      IconData(0xeb6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture_f =
      IconData(0xeb6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture =
      IconData(0xeb6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pictures_f =
      IconData(0xeb6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pictures =
      IconData(0xeb6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart_alt =
      IconData(0xeb6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart_f =
      IconData(0xeb70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pie_chart =
      IconData(0xeb71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_alt_f =
      IconData(0xeb72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_alt =
      IconData(0xeb73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_f =
      IconData(0xeb74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xeb75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest_circle =
      IconData(0xeb76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest_square =
      IconData(0xeb77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest =
      IconData(0xeb78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pizza_slice =
      IconData(0xeb79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_f =
      IconData(0xeb7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane =
      IconData(0xeb7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle_f =
      IconData(0xeb7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle =
      IconData(0xeb7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_square_f =
      IconData(0xeb7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_square =
      IconData(0xeb7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play =
      IconData(0xeb80, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug_f =
      IconData(0xeb81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plug =
      IconData(0xeb82, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle_f =
      IconData(0xeb83, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle =
      IconData(0xeb84, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_rectangle_f =
      IconData(0xeb85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_rectangle =
      IconData(0xeb86, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus =
      IconData(0xeb87, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocket_watch_f =
      IconData(0xeb88, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocket_watch =
      IconData(0xeb89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData podcast =
      IconData(0xeb8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power =
      IconData(0xeb8b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer_f =
      IconData(0xeb8c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData printer =
      IconData(0xeb8d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code =
      IconData(0xeb8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora_circle =
      IconData(0xeb8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora_square =
      IconData(0xeb90, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora =
      IconData(0xeb91, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rainbow =
      IconData(0xeb92, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rec =
      IconData(0xeb93, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle_f =
      IconData(0xeb94, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rectangle =
      IconData(0xeb95, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit =
      IconData(0xeb96, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo =
      IconData(0xeb97, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_reverse =
      IconData(0xeb98, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh =
      IconData(0xeb99, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat =
      IconData(0xeb9a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket_f =
      IconData(0xeb9b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket =
      IconData(0xeb9c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_feed =
      IconData(0xeb9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rubber =
      IconData(0xeb9e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler_f =
      IconData(0xeb9f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruler =
      IconData(0xeba0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save_f =
      IconData(0xeba1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xeba2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors =
      IconData(0xeba3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_f =
      IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen =
      IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screwdriver_f =
      IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screwdriver =
      IconData(0xeba7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_folder =
      IconData(0xeba8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_minus =
      IconData(0xeba9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_plus =
      IconData(0xebaa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search =
      IconData(0xebab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_backward_circle_f =
      IconData(0xebac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_backward_circle =
      IconData(0xebad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_backward_square_f =
      IconData(0xebae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_backward_square =
      IconData(0xebaf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_backward =
      IconData(0xebb0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_forward_circle_f =
      IconData(0xebb1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_forward_circle =
      IconData(0xebb2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_forward_square_f =
      IconData(0xebb3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_forward_square =
      IconData(0xebb4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_forward =
      IconData(0xebb5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_square_f =
      IconData(0xebb6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData set_square =
      IconData(0xebb7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_alt =
      IconData(0xebb8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_alt_f =
      IconData(0xebb9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_alt =
      IconData(0xebba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share =
      IconData(0xebbb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check_f =
      IconData(0xebbc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_check =
      IconData(0xebbd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_close_f =
      IconData(0xebbe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_close =
      IconData(0xebbf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_f =
      IconData(0xebc0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_half =
      IconData(0xebc1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_minus_f =
      IconData(0xebc2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_minus =
      IconData(0xebc3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_plus_f =
      IconData(0xebc4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield_plus =
      IconData(0xebc5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield =
      IconData(0xebc6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify_circle =
      IconData(0xebc7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify_square =
      IconData(0xebc8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify =
      IconData(0xebc9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_alt_f =
      IconData(0xebca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_alt =
      IconData(0xebcb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_f =
      IconData(0xebcc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag =
      IconData(0xebcd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart =
      IconData(0xebce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shuffle =
      IconData(0xebcf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal =
      IconData(0xebd0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sitemap_f =
      IconData(0xebd1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sitemap =
      IconData(0xebd2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull_f =
      IconData(0xebd3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull =
      IconData(0xebd4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype_circle =
      IconData(0xebd5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype_square =
      IconData(0xebd6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype =
      IconData(0xebd7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack_circle =
      IconData(0xebd8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack_square =
      IconData(0xebd9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack =
      IconData(0xebda, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_f =
      IconData(0xebdb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley =
      IconData(0xebdc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_circle =
      IconData(0xebdd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_square =
      IconData(0xebde, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat =
      IconData(0xebdf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowboard_f =
      IconData(0xebe0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowboard =
      IconData(0xebe1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake =
      IconData(0xebe2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud =
      IconData(0xebe3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker_f =
      IconData(0xebe4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaker =
      IconData(0xebe5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify =
      IconData(0xebe6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_f =
      IconData(0xebe7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square =
      IconData(0xebe8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squarespace_circle =
      IconData(0xebe9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squarespace_square =
      IconData(0xebea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squarespace =
      IconData(0xebeb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow_circle =
      IconData(0xebec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow_square =
      IconData(0xebed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stackoverflow =
      IconData(0xebee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stamp_f =
      IconData(0xebef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stamp =
      IconData(0xebf0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_f =
      IconData(0xebf1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_full =
      IconData(0xebf2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_half =
      IconData(0xebf3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star =
      IconData(0xebf4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData station =
      IconData(0xebf5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_sign =
      IconData(0xebf6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop =
      IconData(0xebf7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store =
      IconData(0xebf8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strikethrough =
      IconData(0xebf9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon_circle =
      IconData(0xebfa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon_square =
      IconData(0xebfb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon =
      IconData(0xebfc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_f =
      IconData(0xebfd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun =
      IconData(0xebfe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_left_f =
      IconData(0xebff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_left =
      IconData(0xec00, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_right_f =
      IconData(0xec01, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_right =
      IconData(0xec02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sword_f =
      IconData(0xec03, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sword =
      IconData(0xec04, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet_f =
      IconData(0xec05, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet =
      IconData(0xec06, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_f =
      IconData(0xec07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag =
      IconData(0xec08, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags_f =
      IconData(0xec09, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags =
      IconData(0xec0a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      IconData(0xec0b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_list_f =
      IconData(0xec0c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task_list =
      IconData(0xec0d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature =
      IconData(0xec0e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terminal =
      IconData(0xec0f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunder_f =
      IconData(0xec10, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thunder =
      IconData(0xec11, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket_f =
      IconData(0xec12, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket =
      IconData(0xec13, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools_f =
      IconData(0xec14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools =
      IconData(0xec15, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torch_f =
      IconData(0xec16, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData torch =
      IconData(0xec17, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData totem =
      IconData(0xec18, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train_f =
      IconData(0xec19, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData train =
      IconData(0xec1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender =
      IconData(0xec1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_alt_f =
      IconData(0xec1c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_alt =
      IconData(0xec1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_f =
      IconData(0xec1e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash =
      IconData(0xec1f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_alt_f =
      IconData(0xec20, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_alt =
      IconData(0xec21, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree_f =
      IconData(0xec22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree =
      IconData(0xec23, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trello =
      IconData(0xec24, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_danger_f =
      IconData(0xec25, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_danger =
      IconData(0xec26, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle_f =
      IconData(0xec27, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangle =
      IconData(0xec28, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy_f =
      IconData(0xec29, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy =
      IconData(0xec2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tube =
      IconData(0xec2b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr_circle =
      IconData(0xec2c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr_square =
      IconData(0xec2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr =
      IconData(0xec2e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch =
      IconData(0xec2f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circle =
      IconData(0xec30, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_square =
      IconData(0xec31, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter =
      IconData(0xec32, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella_closed_f =
      IconData(0xec33, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella_closed =
      IconData(0xec34, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella_f =
      IconData(0xec35, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella =
      IconData(0xec36, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData underline =
      IconData(0xec37, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo =
      IconData(0xec38, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unindent =
      IconData(0xec39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData universe =
      IconData(0xec3a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unordered_list =
      IconData(0xec3b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash_circle =
      IconData(0xec3c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash_square =
      IconData(0xec3d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unsplash =
      IconData(0xec3e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
      IconData(0xec3f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle =
      IconData(0xec40, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_minus =
      IconData(0xec41, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus =
      IconData(0xec42, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_remove =
      IconData(0xec43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_square =
      IconData(0xec44, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xec45, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users =
      IconData(0xec46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viadeo =
      IconData(0xec47, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber_circle =
      IconData(0xec48, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber_square =
      IconData(0xec49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber =
      IconData(0xec4a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera_f =
      IconData(0xec4b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera_vintage_f =
      IconData(0xec4c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera_vintage =
      IconData(0xec4d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_camera =
      IconData(0xec4e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo_circle =
      IconData(0xec4f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo_square =
      IconData(0xec50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo =
      IconData(0xec51, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vine_circle =
      IconData(0xec52, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vine_square =
      IconData(0xec53, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vine =
      IconData(0xec54, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData voicemail =
      IconData(0xec55, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_circle_f =
      IconData(0xec56, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_circle =
      IconData(0xec57, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down_circle_f =
      IconData(0xec58, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down_circle =
      IconData(0xec59, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down_square_f =
      IconData(0xec5a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down_square =
      IconData(0xec5b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down =
      IconData(0xec5c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute_circle_f =
      IconData(0xec5d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute_circle =
      IconData(0xec5e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute_square_f =
      IconData(0xec5f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute_square =
      IconData(0xec60, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_mute =
      IconData(0xec61, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_square_f =
      IconData(0xec62, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_square =
      IconData(0xec63, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_circle_f =
      IconData(0xec64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_circle =
      IconData(0xec65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_square_f =
      IconData(0xec66, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up_square =
      IconData(0xec67, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up =
      IconData(0xec68, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume =
      IconData(0xec69, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch_f =
      IconData(0xec6a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData watch =
      IconData(0xec6b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drop_f =
      IconData(0xec6c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drop =
      IconData(0xec6d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp =
      IconData(0xec6e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi =
      IconData(0xec6f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikipedia =
      IconData(0xec70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wordpress =
      IconData(0xec71, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData world =
      IconData(0xec72, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench_f =
      IconData(0xec73, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench =
      IconData(0xec74, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write_f =
      IconData(0xec75, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write =
      IconData(0xec76, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo_circle =
      IconData(0xec77, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo_square =
      IconData(0xec78, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo =
      IconData(0xec79, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp_circle =
      IconData(0xec7a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp_square =
      IconData(0xec7b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp =
      IconData(0xec7c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_circle =
      IconData(0xec7d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_square =
      IconData(0xec7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube =
      IconData(0xec7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
