include: package:lint/analysis_options.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    parameter_assignments: ignore
    file_names: ignore
    dead_code: warning
    unused_element: warning
    unused_field: warning
    unused_local_variable: warning
  exclude:
    - lib/theme/jam_icons_icons.dart
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - '**/*.config.dart'
