// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(List<Object?>? replyList, String channelName, {required bool isNullValid}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum SaveMediaKind { wallpaper, setup }

class SaveMediaRequest {
  SaveMediaRequest({required this.link, required this.isLocalFile, required this.kind});

  String link;

  bool isLocalFile;

  SaveMediaKind kind;

  List<Object?> _toList() {
    return <Object?>[link, isLocalFile, kind];
  }

  Object encode() {
    return _toList();
  }

  static SaveMediaRequest decode(Object result) {
    result as List<Object?>;
    return SaveMediaRequest(
      link: result[0]! as String,
      isLocalFile: result[1]! as bool,
      kind: result[2]! as SaveMediaKind,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SaveMediaRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(link, other.link) &&
        _deepEquals(isLocalFile, other.isLocalFile) &&
        _deepEquals(kind, other.kind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class DownloadRequest {
  DownloadRequest({required this.link, required this.filenameWithoutExtension});

  String link;

  String filenameWithoutExtension;

  List<Object?> _toList() {
    return <Object?>[link, filenameWithoutExtension];
  }

  Object encode() {
    return _toList();
  }

  static DownloadRequest decode(Object result) {
    result as List<Object?>;
    return DownloadRequest(link: result[0]! as String, filenameWithoutExtension: result[1]! as String);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(link, other.link) && _deepEquals(filenameWithoutExtension, other.filenameWithoutExtension);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class OperationResult {
  OperationResult({required this.success, this.errorCode, this.message});

  bool success;

  String? errorCode;

  String? message;

  List<Object?> _toList() {
    return <Object?>[success, errorCode, message];
  }

  Object encode() {
    return _toList();
  }

  static OperationResult decode(Object result) {
    result as List<Object?>;
    return OperationResult(success: result[0]! as bool, errorCode: result[1] as String?, message: result[2] as String?);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OperationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class DownloadItemsResult {
  DownloadItemsResult({required this.success, required this.items, this.errorCode, this.message});

  bool success;

  List<String> items;

  String? errorCode;

  String? message;

  List<Object?> _toList() {
    return <Object?>[success, items, errorCode, message];
  }

  Object encode() {
    return _toList();
  }

  static DownloadItemsResult decode(Object result) {
    result as List<Object?>;
    return DownloadItemsResult(
      success: result[0]! as bool,
      items: (result[1]! as List<Object?>).cast<String>(),
      errorCode: result[2] as String?,
      message: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DownloadItemsResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) &&
        _deepEquals(items, other.items) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is SaveMediaKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is SaveMediaRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is DownloadRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is OperationResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is DownloadItemsResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : SaveMediaKind.values[value];
      case 130:
        return SaveMediaRequest.decode(readValue(buffer)!);
      case 131:
        return DownloadRequest.decode(readValue(buffer)!);
      case 132:
        return OperationResult.decode(readValue(buffer)!);
      case 133:
        return DownloadItemsResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PrismMediaHostApi {
  /// Constructor for [PrismMediaHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PrismMediaHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<OperationResult> saveMedia(SaveMediaRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OperationResult;
  }

  Future<OperationResult> enqueueDownload(DownloadRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OperationResult;
  }

  Future<DownloadItemsResult> listDownloads() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.Prism.PrismMediaHostApi.listDownloads$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as DownloadItemsResult;
  }

  Future<OperationResult> clearDownloads() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.Prism.PrismMediaHostApi.clearDownloads$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OperationResult;
  }
}
