default_platform(:android)

platform :android do
  desc "Deploy to closed beta track"
  lane :beta do
    begin
      # gradle(task: "clean")
      # gradle(
      #   task: "bundle",
      #   build_type: 'Release'
      # )
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
        version_code: flutter_version()["version_code"],
      )
    end
  end
end