import 'package:Prism/core/analytics/events/analytics_enums.dart';
import 'package:Prism/core/coins/coin_action.dart';
import 'package:Prism/core/platform/wallpaper_service.dart';
import 'package:Prism/features/ai_wallpaper/domain/entities/ai_charge_mode.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('every analytics enum keeps its wire values', () {
    final Map<String, List<String>> actual = <String, List<String>>{
      'WallpaperTarget': WallpaperTarget.values.map((v) => v.wireValue).toList(),
      'BinaryResultValue': BinaryResultValue.values.map((v) => v.wireValue).toList(),
      'RcOrFallbackValue': RcOrFallbackValue.values.map((v) => v.wireValue).toList(),
      'PaywallResultValue': PaywallResultValue.values.map((v) => v.wireValue).toList(),
      'SubscriptionEntitlementRefreshResultValue': SubscriptionEntitlementRefreshResultValue.values
          .map((v) => v.wireValue)
          .toList(),
      'CoinEarnAction': CoinEarnAction.values.map((v) => v.wireValue).toList(),
      'CoinSpendAction': CoinSpendAction.values.map((v) => v.wireValue).toList(),
      'AiChargeMode': AiChargeMode.values.map((v) => v.wireValue).toList(),
      'SettingValue': SettingValue.values.map((v) => v.wireValue).toList(),
      'AnalyticsActionValue': AnalyticsActionValue.values.map((v) => v.wireValue).toList(),
      'EventResultValue': EventResultValue.values.map((v) => v.wireValue).toList(),
      'AnalyticsReasonValue': AnalyticsReasonValue.values.map((v) => v.wireValue).toList(),
      'SearchProviderValue': SearchProviderValue.values.map((v) => v.wireValue).toList(),
      'ItemTypeValue': ItemTypeValue.values.map((v) => v.wireValue).toList(),
      'TargetTypeValue': TargetTypeValue.values.map((v) => v.wireValue).toList(),
      'EntryPointValue': EntryPointValue.values.map((v) => v.wireValue).toList(),
      'LaunchStateValue': LaunchStateValue.values.map((v) => v.wireValue).toList(),
      'ShareChannelValue': ShareChannelValue.values.map((v) => v.wireValue).toList(),
      'DismissModeValue': DismissModeValue.values.map((v) => v.wireValue).toList(),
      'NotificationTypeValue': NotificationTypeValue.values.map((v) => v.wireValue).toList(),
      'AuthMethodValue': AuthMethodValue.values.map((v) => v.wireValue).toList(),
      'NavTabValue': NavTabValue.values.map((v) => v.wireValue).toList(),
      'NotificationPreferenceValue': NotificationPreferenceValue.values.map((v) => v.wireValue).toList(),
      'DeepLinkSourceValue': DeepLinkSourceValue.values.map((v) => v.wireValue).toList(),
      'ShareTypeValue': ShareTypeValue.values.map((v) => v.wireValue).toList(),
      'AnalyticsSurfaceValue': AnalyticsSurfaceValue.values.map((v) => v.wireValue).toList(),
      'ScrollListNameValue': ScrollListNameValue.values.map((v) => v.wireValue).toList(),
      'ScrollDepthPercentValue': ScrollDepthPercentValue.values.map((v) => v.wireValue).toList(),
      'LinkDestinationValue': LinkDestinationValue.values.map((v) => v.wireValue).toList(),
    };
    expect(actual, <String, List<String>>{
      'WallpaperTarget': <String>['home', 'lock', 'both'],
      'BinaryResultValue': <String>['success', 'failure'],
      'RcOrFallbackValue': <String>['rc_attempt', 'fallback_only', 'rc'],
      'PaywallResultValue': <String>[
        'placement_overridden_to_v3',
        'no_offering',
        'not_presented',
        'error',
        'cancelled',
        'purchased',
        'restored',
        'rc_error',
        'unknown',
      ],
      'SubscriptionEntitlementRefreshResultValue': <String>['success', 'failure'],
      'CoinEarnAction': <String>[
        'rewarded_ad',
        'daily_login',
        'streak_bonus',
        'first_wallpaper_upload',
        'referral',
        'profile_completion',
        'pro_daily_bonus',
        'refund',
      ],
      'CoinSpendAction': <String>[
        'wallpaper_download',
        'premium_wallpaper_download',
        'ai_generation',
        'premium_filter',
        'premium_preview_24h',
        'streak_freeze',
      ],
      'AiChargeMode': <String>['free_trial', 'pro_included', 'coin_spend', 'insufficient'],
      'SettingValue': <String>['anime_wallpapers', 'sketchy_wallpapers', 'recommendations_notifications', 'haptics'],
      'AnalyticsActionValue': <String>[
        'buy_premium_tapped',
        'clear_cache_tapped',
        'restart_app_tapped',
        'restore_purchase_tapped',
        'sign_in_tapped',
        'logout_tapped',
        'clear_favourite_walls_tapped',
        'clear_favourite_walls_confirmed',
        'upload_sheet_opened',
        'upload_wallpaper_selected',
        'upload_ai_selected',
        'notification_settings_opened',
        'quick_action_follow_feed',
        'quick_action_collections',
        'quick_action_downloads',
        'quick_action_unknown',
        'back_tapped',
        'clock_overlay_opened',
        'panel_opened',
        'panel_closed',
        'panel_collapse_tapped',
        'palette_cycle_tapped',
        'palette_reset_long_pressed',
        'follow_tapped',
        'unfollow_tapped',
        'edit_profile_tapped',
        'open_drawer_tapped',
        'drawer_fav_walls_tapped',
        'drawer_downloads_tapped',
        'drawer_share_prism_tapped',
        'drawer_logout_tapped',
        'open_downloaded_wallpaper_tapped',
        'open_transaction_link_tapped',
        'action_chip_tapped',
        'contributor_profile_tapped',
        'banner_tapped',
        'carousel_item_opened',
        'tile_opened',
        'see_more_tapped',
      ],
      'EventResultValue': <String>['success', 'failure', 'cancelled', 'blocked', 'navigated', 'empty'],
      'AnalyticsReasonValue': <String>[
        'user_cancelled',
        'error',
        'missing_data',
        'not_signed_in',
        'empty_input',
        'unknown',
      ],
      'SearchProviderValue': <String>['wallhaven', 'pexels', 'prism'],
      'ItemTypeValue': <String>['wallpaper', 'user'],
      'TargetTypeValue': <String>['share', 'user', 'setup', 'refer', 'short_code', 'unknown'],
      'EntryPointValue': <String>['bottom_nav'],
      'LaunchStateValue': <String>['initial_launch', 'foreground'],
      'ShareChannelValue': <String>['share_sheet', 'link'],
      'DismissModeValue': <String>['swipe'],
      'NotificationTypeValue': <String>['route', 'external_url', 'unknown'],
      'AuthMethodValue': <String>['google', 'apple'],
      'NavTabValue': <String>['home', 'search', 'streak', 'collection'],
      'NotificationPreferenceValue': <String>['followers', 'posts', 'in_app', 'recommendations', 'streak_reminders'],
      'DeepLinkSourceValue': <String>['app_links'],
      'ShareTypeValue': <String>['wallpaper', 'user', 'refer'],
      'AnalyticsSurfaceValue': <String>[
        'wallpaper_screen',
        'share_wallpaper_view',
        'search_wallpaper_screen',
        'favourite_wallpaper_view',
        'profile_wallpaper_view',
        'download_wallpaper_screen',
        'profile_screen',
        'profile_drawer',
        'profile_prism_list',
        'about_screen',
        'coin_transactions_screen',
        'download_screen',
        'home_wallpaper_grid',
        'home_wallhaven_grid',
        'home_pexels_grid',
        'home_color_grid',
        'home_collections_view_grid',
        'favourite_walls_grid',
      ],
      'ScrollListNameValue': <String>[
        'wallpaper_grid',
        'wallhaven_grid',
        'pexels_grid',
        'color_grid',
        'collections_view_grid',
        'favourite_walls_grid',
      ],
      'ScrollDepthPercentValue': <String>['p25', 'p50', 'p75', 'p100'],
      'LinkDestinationValue': <String>['github', 'play_store', 'twitter', 'instagram', 'telegram', 'email', 'external'],
    });
  });

  test('paywallResultValueFromSdkName maps SDK results and defaults to unknown', () {
    expect(paywallResultValueFromSdkName('notPresented'), PaywallResultValue.notPresented);
    expect(paywallResultValueFromSdkName('error'), PaywallResultValue.error);
    expect(paywallResultValueFromSdkName(' cancelled '), PaywallResultValue.cancelled);
    expect(paywallResultValueFromSdkName('purchased'), PaywallResultValue.purchased);
    expect(paywallResultValueFromSdkName('restored'), PaywallResultValue.restored);
    expect(paywallResultValueFromSdkName('somethingNew'), PaywallResultValue.unknown);
  });
}
