// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPrismMediaApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPrismMediaApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPrismMediaApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPrismMediaApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPrismMediaApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPrismMediaApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum SaveMediaKind: Int {
  case wallpaper = 0
  case setup = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct SaveMediaRequest: Hashable {
  var link: String
  var isLocalFile: Bool
  var kind: SaveMediaKind


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SaveMediaRequest? {
    let link = pigeonVar_list[0] as! String
    let isLocalFile = pigeonVar_list[1] as! Bool
    let kind = pigeonVar_list[2] as! SaveMediaKind

    return SaveMediaRequest(
      link: link,
      isLocalFile: isLocalFile,
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      link,
      isLocalFile,
      kind,
    ]
  }
  static func == (lhs: SaveMediaRequest, rhs: SaveMediaRequest) -> Bool {
    return deepEqualsPrismMediaApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrismMediaApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadRequest: Hashable {
  var link: String
  var filenameWithoutExtension: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadRequest? {
    let link = pigeonVar_list[0] as! String
    let filenameWithoutExtension = pigeonVar_list[1] as! String

    return DownloadRequest(
      link: link,
      filenameWithoutExtension: filenameWithoutExtension
    )
  }
  func toList() -> [Any?] {
    return [
      link,
      filenameWithoutExtension,
    ]
  }
  static func == (lhs: DownloadRequest, rhs: DownloadRequest) -> Bool {
    return deepEqualsPrismMediaApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrismMediaApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OperationResult: Hashable {
  var success: Bool
  var errorCode: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OperationResult? {
    let success = pigeonVar_list[0] as! Bool
    let errorCode: String? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])

    return OperationResult(
      success: success,
      errorCode: errorCode,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorCode,
      message,
    ]
  }
  static func == (lhs: OperationResult, rhs: OperationResult) -> Bool {
    return deepEqualsPrismMediaApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPrismMediaApi(value: toList(), hasher: &hasher)
  }
}

private class PrismMediaApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SaveMediaKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SaveMediaRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return DownloadRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return OperationResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PrismMediaApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SaveMediaKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SaveMediaRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OperationResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PrismMediaApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PrismMediaApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PrismMediaApiPigeonCodecWriter(data: data)
  }
}

class PrismMediaApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PrismMediaApiPigeonCodec(readerWriter: PrismMediaApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PrismMediaHostApi {
  func saveMedia(request: SaveMediaRequest) throws -> OperationResult
  func enqueueDownload(request: DownloadRequest) throws -> OperationResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PrismMediaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrismMediaApiPigeonCodec.shared }
  /// Sets up an instance of `PrismMediaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PrismMediaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let saveMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveMediaRequest
        do {
          let result = try api.saveMedia(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveMediaChannel.setMessageHandler(nil)
    }
    let enqueueDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enqueueDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DownloadRequest
        do {
          let result = try api.enqueueDownload(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enqueueDownloadChannel.setMessageHandler(nil)
    }
  }
}
