// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsPrismMediaApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashPrismMediaApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsPrismMediaApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsPrismMediaApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsPrismMediaApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsPrismMediaApi(lhsKey, rhsKey) {
          if deepEqualsPrismMediaApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsPrismMediaApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashPrismMediaApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashPrismMediaApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashPrismMediaApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashPrismMediaApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashPrismMediaApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashPrismMediaApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum SaveMediaKind: Int {
  case wallpaper = 0
  case setup = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct SaveMediaRequest: Hashable {
  var link: String
  var isLocalFile: Bool
  var kind: SaveMediaKind


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SaveMediaRequest? {
    let link = pigeonVar_list[0] as! String
    let isLocalFile = pigeonVar_list[1] as! Bool
    let kind = pigeonVar_list[2] as! SaveMediaKind

    return SaveMediaRequest(
      link: link,
      isLocalFile: isLocalFile,
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      link,
      isLocalFile,
      kind,
    ]
  }
  static func == (lhs: SaveMediaRequest, rhs: SaveMediaRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrismMediaApi(lhs.link, rhs.link) && deepEqualsPrismMediaApi(lhs.isLocalFile, rhs.isLocalFile) && deepEqualsPrismMediaApi(lhs.kind, rhs.kind)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SaveMediaRequest")
    deepHashPrismMediaApi(value: link, hasher: &hasher)
    deepHashPrismMediaApi(value: isLocalFile, hasher: &hasher)
    deepHashPrismMediaApi(value: kind, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadRequest: Hashable {
  var link: String
  var filenameWithoutExtension: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadRequest? {
    let link = pigeonVar_list[0] as! String
    let filenameWithoutExtension = pigeonVar_list[1] as! String

    return DownloadRequest(
      link: link,
      filenameWithoutExtension: filenameWithoutExtension
    )
  }
  func toList() -> [Any?] {
    return [
      link,
      filenameWithoutExtension,
    ]
  }
  static func == (lhs: DownloadRequest, rhs: DownloadRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrismMediaApi(lhs.link, rhs.link) && deepEqualsPrismMediaApi(lhs.filenameWithoutExtension, rhs.filenameWithoutExtension)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadRequest")
    deepHashPrismMediaApi(value: link, hasher: &hasher)
    deepHashPrismMediaApi(value: filenameWithoutExtension, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OperationResult: Hashable {
  var success: Bool
  var errorCode: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OperationResult? {
    let success = pigeonVar_list[0] as! Bool
    let errorCode: String? = nilOrValue(pigeonVar_list[1])
    let message: String? = nilOrValue(pigeonVar_list[2])

    return OperationResult(
      success: success,
      errorCode: errorCode,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorCode,
      message,
    ]
  }
  static func == (lhs: OperationResult, rhs: OperationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrismMediaApi(lhs.success, rhs.success) && deepEqualsPrismMediaApi(lhs.errorCode, rhs.errorCode) && deepEqualsPrismMediaApi(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OperationResult")
    deepHashPrismMediaApi(value: success, hasher: &hasher)
    deepHashPrismMediaApi(value: errorCode, hasher: &hasher)
    deepHashPrismMediaApi(value: message, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadItemsResult: Hashable {
  var success: Bool
  var items: [String]
  var errorCode: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadItemsResult? {
    let success = pigeonVar_list[0] as! Bool
    let items = pigeonVar_list[1] as! [String]
    let errorCode: String? = nilOrValue(pigeonVar_list[2])
    let message: String? = nilOrValue(pigeonVar_list[3])

    return DownloadItemsResult(
      success: success,
      items: items,
      errorCode: errorCode,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      items,
      errorCode,
      message,
    ]
  }
  static func == (lhs: DownloadItemsResult, rhs: DownloadItemsResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsPrismMediaApi(lhs.success, rhs.success) && deepEqualsPrismMediaApi(lhs.items, rhs.items) && deepEqualsPrismMediaApi(lhs.errorCode, rhs.errorCode) && deepEqualsPrismMediaApi(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DownloadItemsResult")
    deepHashPrismMediaApi(value: success, hasher: &hasher)
    deepHashPrismMediaApi(value: items, hasher: &hasher)
    deepHashPrismMediaApi(value: errorCode, hasher: &hasher)
    deepHashPrismMediaApi(value: message, hasher: &hasher)
  }
}

private class PrismMediaApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SaveMediaKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SaveMediaRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return DownloadRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return OperationResult.fromList(self.readValue() as! [Any?])
    case 133:
      return DownloadItemsResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PrismMediaApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SaveMediaKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SaveMediaRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? OperationResult {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadItemsResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PrismMediaApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PrismMediaApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PrismMediaApiPigeonCodecWriter(data: data)
  }
}

class PrismMediaApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PrismMediaApiPigeonCodec(readerWriter: PrismMediaApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PrismMediaHostApi {
  func saveMedia(request: SaveMediaRequest) throws -> OperationResult
  func enqueueDownload(request: DownloadRequest) throws -> OperationResult
  func listDownloads() throws -> DownloadItemsResult
  func clearDownloads() throws -> OperationResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PrismMediaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PrismMediaApiPigeonCodec.shared }
  /// Sets up an instance of `PrismMediaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PrismMediaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let saveMediaChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SaveMediaRequest
        do {
          let result = try api.saveMedia(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveMediaChannel.setMessageHandler(nil)
    }
    let enqueueDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enqueueDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DownloadRequest
        do {
          let result = try api.enqueueDownload(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enqueueDownloadChannel.setMessageHandler(nil)
    }
    let listDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.listDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listDownloadsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.listDownloads()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listDownloadsChannel.setMessageHandler(nil)
    }
    let clearDownloadsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.Prism.PrismMediaHostApi.clearDownloads\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearDownloadsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.clearDownloads()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearDownloadsChannel.setMessageHandler(nil)
    }
  }
}
