// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hash.prism.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrismMediaApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SaveMediaKind(val raw: Int) {
  WALLPAPER(0),
  SETUP(1);

  companion object {
    fun ofRaw(raw: Int): SaveMediaKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SaveMediaRequest (
  val link: String,
  val isLocalFile: Boolean,
  val kind: SaveMediaKind
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SaveMediaRequest {
      val link = pigeonVar_list[0] as String
      val isLocalFile = pigeonVar_list[1] as Boolean
      val kind = pigeonVar_list[2] as SaveMediaKind
      return SaveMediaRequest(link, isLocalFile, kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      link,
      isLocalFile,
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SaveMediaRequest
    return PrismMediaApiPigeonUtils.deepEquals(this.link, other.link) && PrismMediaApiPigeonUtils.deepEquals(this.isLocalFile, other.isLocalFile) && PrismMediaApiPigeonUtils.deepEquals(this.kind, other.kind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.link)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.isLocalFile)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.kind)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadRequest (
  val link: String,
  val filenameWithoutExtension: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadRequest {
      val link = pigeonVar_list[0] as String
      val filenameWithoutExtension = pigeonVar_list[1] as String
      return DownloadRequest(link, filenameWithoutExtension)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      link,
      filenameWithoutExtension,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadRequest
    return PrismMediaApiPigeonUtils.deepEquals(this.link, other.link) && PrismMediaApiPigeonUtils.deepEquals(this.filenameWithoutExtension, other.filenameWithoutExtension)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.link)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.filenameWithoutExtension)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OperationResult (
  val success: Boolean,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OperationResult {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as String?
      val message = pigeonVar_list[2] as String?
      return OperationResult(success, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OperationResult
    return PrismMediaApiPigeonUtils.deepEquals(this.success, other.success) && PrismMediaApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && PrismMediaApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.success)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.message)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadItemsResult (
  val success: Boolean,
  val items: List<String>,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadItemsResult {
      val success = pigeonVar_list[0] as Boolean
      val items = pigeonVar_list[1] as List<String>
      val errorCode = pigeonVar_list[2] as String?
      val message = pigeonVar_list[3] as String?
      return DownloadItemsResult(success, items, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      items,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DownloadItemsResult
    return PrismMediaApiPigeonUtils.deepEquals(this.success, other.success) && PrismMediaApiPigeonUtils.deepEquals(this.items, other.items) && PrismMediaApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && PrismMediaApiPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.success)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.items)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + PrismMediaApiPigeonUtils.deepHash(this.message)
    return result
  }
}
private open class PrismMediaApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SaveMediaKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SaveMediaRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OperationResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadItemsResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SaveMediaKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SaveMediaRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DownloadRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OperationResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DownloadItemsResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PrismMediaHostApi {
  fun saveMedia(request: SaveMediaRequest): OperationResult
  fun enqueueDownload(request: DownloadRequest): OperationResult
  fun listDownloads(): DownloadItemsResult
  fun clearDownloads(): OperationResult

  companion object {
    /** The codec used by PrismMediaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrismMediaApiPigeonCodec()
    }
    /** Sets up an instance of `PrismMediaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PrismMediaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SaveMediaRequest
            val wrapped: List<Any?> = try {
              listOf(api.saveMedia(requestArg))
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DownloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.enqueueDownload(requestArg))
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.listDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listDownloads())
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.clearDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.clearDownloads())
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
