// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hash.prism.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PrismMediaApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class SaveMediaKind(val raw: Int) {
  WALLPAPER(0),
  SETUP(1);

  companion object {
    fun ofRaw(raw: Int): SaveMediaKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SaveMediaRequest (
  val link: String,
  val isLocalFile: Boolean,
  val kind: SaveMediaKind
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SaveMediaRequest {
      val link = pigeonVar_list[0] as String
      val isLocalFile = pigeonVar_list[1] as Boolean
      val kind = pigeonVar_list[2] as SaveMediaKind
      return SaveMediaRequest(link, isLocalFile, kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      link,
      isLocalFile,
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SaveMediaRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrismMediaApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadRequest (
  val link: String,
  val filenameWithoutExtension: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadRequest {
      val link = pigeonVar_list[0] as String
      val filenameWithoutExtension = pigeonVar_list[1] as String
      return DownloadRequest(link, filenameWithoutExtension)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      link,
      filenameWithoutExtension,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DownloadRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrismMediaApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OperationResult (
  val success: Boolean,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OperationResult {
      val success = pigeonVar_list[0] as Boolean
      val errorCode = pigeonVar_list[1] as String?
      val message = pigeonVar_list[2] as String?
      return OperationResult(success, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OperationResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrismMediaApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DownloadItemsResult (
  val success: Boolean,
  val items: List<String>,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DownloadItemsResult {
      val success = pigeonVar_list[0] as Boolean
      val items = pigeonVar_list[1] as List<String>
      val errorCode = pigeonVar_list[2] as String?
      val message = pigeonVar_list[3] as String?
      return DownloadItemsResult(success, items, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      items,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DownloadItemsResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PrismMediaApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PrismMediaApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SaveMediaKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SaveMediaRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OperationResult.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DownloadItemsResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SaveMediaKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SaveMediaRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DownloadRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is OperationResult -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is DownloadItemsResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PrismMediaHostApi {
  fun saveMedia(request: SaveMediaRequest): OperationResult
  fun enqueueDownload(request: DownloadRequest): OperationResult
  fun listDownloads(): DownloadItemsResult
  fun clearDownloads(): OperationResult

  companion object {
    /** The codec used by PrismMediaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PrismMediaApiPigeonCodec()
    }
    /** Sets up an instance of `PrismMediaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PrismMediaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.saveMedia$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SaveMediaRequest
            val wrapped: List<Any?> = try {
              listOf(api.saveMedia(requestArg))
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.enqueueDownload$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DownloadRequest
            val wrapped: List<Any?> = try {
              listOf(api.enqueueDownload(requestArg))
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.listDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.listDownloads())
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.Prism.PrismMediaHostApi.clearDownloads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.clearDownloads())
            } catch (exception: Throwable) {
              PrismMediaApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
